### ISSUE TITLE
How to add a single image for prediction?

### ISSUE THREAD

**Issue by technoartista** [thekevinscott/ml-classifier-ui#3]
I have downloaded the trained model . When i import it into my code i get few error
Uncaught (in promise) Error: Based on the provided shape, [12544,100], and dtype float32, the tensor should have 1254400 values but has 0

Do you have any sample code for loading a pretrained model and run prediction just for 1 image

**Comment by thekevinscott** [comment]
Hi @technoartista, can you share the code or a repo with the bug?

**Comment by Elvincth** [comment]
Same problem here, if you can provide us a sample code of predicting image would be great! Thanks

**Comment by thekevinscott** [comment]
Check out https://thekevinscott.com/image-classification-with-javascript/
