### ISSUE TITLE
How to get started?

### ISSUE THREAD

**Issue by SamuelReinfelder** [thekevinscott/ml-classifier-ui#4]
I am familiar with html/js/css, but not react.

I can't figure out how to get started. The Quick start section did not really help me. Any link/additional info how i can use this code for generating a html page?

Sam

**Comment by thekevinscott** [comment]
Hi @SamuelReinfelder,

I set up a codesandbox here that demonstrates it in action:

https://codesandbox.io/s/218po5mzxn

It is written in React so you will need to use the component within the context of a React application.

If you're not using React, I'd recommend checking out the standalone piece, [`ml-classifier`](http://github.com/thekevinscott/ml-classifier), which has no associated UI and is just the model and training. You'd need to provide your own mechanism for uploading images and displaying the results but all of the ML work would be handled for you.

And if you'd like to fork a version in Vue or another JS framework, that would be very welcome!
